# Generated by Django 3.1.4 on 2021-03-01 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=200)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('owner_name', models.CharField(max_length=200)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry_date_month', models.CharField(max_length=2)),
                ('expiry_date_year', models.CharField(max_length=4)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
