# Generated by Django 3.1.6 on 2021-03-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('vendor', models.CharField(max_length=200)),
                ('CreditorDebit', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=200)),
                ('category', models.CharField(choices=[('Medical', 'Medical'), ('Groceries', 'Groceries'), ('Food', 'Food'), ('Entertainment', 'Entertainment'), ('Bills', 'Bills'), ('Others', 'Others')], max_length=200)),
                ('month', models.CharField(default='03', editable=False, max_length=2)),
                ('year', models.CharField(default='2021', editable=False, max_length=4)),
            ],
        ),
    ]
