# Generated by Django 3.1.6 on 2021-03-05 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cards.cards'),
            preserve_default=False,
        ),
    ]
