# Generated by Django 3.1.6 on 2021-03-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_transactions_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='owner',
        ),
    ]
