# Generated by Django 3.1.4 on 2021-03-06 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20210305_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='credit',
            field=models.DecimalField(auto_created=True, decimal_places=2, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
