# Generated by Django 3.1.7 on 2021-03-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20210327_1511'),
        ('cards', '0007_auto_20210321_1827'),
    ]

    operations = [
    ]
