# Generated by Django 3.1.7 on 2021-03-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_merge_20210328_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='bank',
            field=models.CharField(choices=[('SBI', 'SBI'), ('HDFC', 'HDFC'), ('Standard Chartered Bank', 'Standard Chartered Bank'), ('YES Bank', 'YES Bank'), ('Citibank', 'Citibank'), ('ICICI Bank', 'ICICI Bank'), ('American Express', 'American Express'), ('IndusInd Bank', 'IndusInd Bank'), ('RBL Bank', 'RBL Bank'), ('Allahabad Bank', 'Allahabad Bank'), ('Bajaj Finserv', 'Bajaj Finserv'), ('Andhra Bank', 'Andhra Bank'), ('Axis Bank', 'Axis Bank'), ('Bank of India', 'Bank of India'), ('Bank of Baroda', 'Bank of Baroda'), ('Bank of Maharashtra', 'Bank of Maharashtra'), ('Canara Bank', 'Canara Bank'), ('Central Bank of India', 'Central Bank of India'), ('DCB Bank', 'DCB Bank'), ('Federal Bank', 'Federal Bank'), ('HSBC Bank', 'HSBC Bank'), ('IDBI Bank', 'IDBI Bank'), ('Indian Bank', 'Indian Bank'), ('Kotak Mahindra Bank', 'Kotak Mahindra Bank'), ('Nainital Bank', 'Nainital Bank'), ('Punjab National Bank', 'Punjab National Bank'), ('Tata Capital', 'Tata Capital'), ('UCO Bank', 'UCO Bank'), ('Union Bank of India', 'Union Bank of India'), ('Vijaya Bank', 'Vijaya Bank')], max_length=200),
        ),
    ]
