# Generated by Django 3.1.6 on 2021-04-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20210330_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='month',
            field=models.CharField(default='04', editable=False, max_length=2),
        ),
    ]
