# Generated by Django 3.1.6 on 2021-04-04 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20210401_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='lastPayDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
