# Generated by Django 3.1.7 on 2021-04-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_cards_lastpaydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='rewards',
            field=models.IntegerField(default=0),
        ),
    ]
